# Generated by Django 4.2 on 2024-01-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('hp', models.SmallIntegerField()),
                ('attack', models.SmallIntegerField()),
                ('defense', models.SmallIntegerField()),
                ('special_attack', models.SmallIntegerField()),
                ('special_defense', models.SmallIntegerField()),
                ('speed', models.SmallIntegerField()),
                ('image', models.CharField(max_length=250)),
                ('type', models.ManyToManyField(to='pokedex.type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
