# Generated by Django 4.2 on 2024-01-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='damage_relations',
            field=models.JSONField(default=list),
        ),
    ]
