# Generated by Django 4.2 on 2024-01-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_pokemonnames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemonnames',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
